### ISSUE TITLE
Using for Sign in with Apple verify token

### ISSUE THREAD

**Issue by ashish-naik** [kreactive/JSONWebToken#17]
Seems this package can be used token verification in Sign in with Apple.

how do I use it exactly? How do i get the secret and compare with "sub"?

When will this package be upgraded to support Swift 5 and Xcode 11?

Thanks
Ashish

**Comment by 5fcgdaeb** [comment]
Swift 5 and XCode 11 support would be great! 👍

**Comment by ashish-naik** [comment]
@g-bourachot is Xcode 11 supporting coming?

**Comment by g-bourachot** [comment]
The package is updated for Xcode 11 and Swift 5. Sorry for the delay

**Comment by ashish-naik** [comment]
Thank you. Current version will work or will be bumped up?

**Comment by g-bourachot** [comment]
Just released a version 2.2.0

**Comment by ashish-naik** [comment]
Thanks
