### ISSUE TITLE
CocoaPods Support / PodSpec Support

### ISSUE THREAD

**Issue by tomjackman** [kreactive/JSONWebToken#9]
Hi @antoinepalazzolo 

I am wondering if it is possible to publish the library? 

Using the git ref `pod 'JSONWebToken', :git => 'https://github.com/kreactive/JSONWebToken.git', :branch => 'master'` only works in a `Podfile` and not a `PodSpec`.

PodSpec's only support the following [format](http://guides.cocoapods.org/syntax/podspec.html#dependency) and don't support using git branches, so its not possible to use the library via a PodSpec.

**Comment by g-bourachot** [comment]
Hi @TommyJ1994 

we just published the library : https://cocoapods.org/pods/KTVJSONWebToken

Could you please tell me if everything works fine for you now ?

**Comment by tomjackman** [comment]
@g-bourachot Thank you, I will test it soon and let you know if all is ok. Closing this issue for now.
